### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by CarlosJa** [lunoxis/Instagram#3]
Fatal error: Uncaught Instagram\Exception\InstagramLoginException: Unknown error, please report it with a GitHub issue. Client error: `POST https://www.instagram.com/accounts/login/ajax/` resulted in a `429 Too Many Requests` response in /home/verifica/public_html/vendor/lunoxis/instagram/src/Login/Instagram.php:63 Stack trace: #0 /home/verifica/public_html/public/controllers/instagram.php(12): Instagram\Login\Instagram->login() #1 /home/verifica/public_html/core/Bootstrap.php(218): instagram->index() #2 /home/verifica/public_html/core/Bootstrap.php(54): Bootstrap->_callControllerMethod() #3 /home/verifica/public_html/public/index.php(14): Bootstrap->init() #4 /home/verifica/public_html/index.php(2): require_once('/home/verifica/...') #5 {main} thrown in /home/verifica/public_html/vendor/lunoxis/instagram/src/Login/Instagram.php on line 63

**Comment by Bitwise-01** [comment]
Unfortunately this repo is no longer maintained
